# Generated by Django 5.0.4 on 2024-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books_images/')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('isbn', models.CharField(max_length=13)),
                ('pages', models.PositiveIntegerField()),
            ],
        ),
    ]
